spring.application.name=tb-alert-backend
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tbAlert
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/tb-alert

jwt.auth.converter.resource-id=tb-alert-frontend
jwt.auth.converter.principal-attribute=preferred_username

keycloak.realm=tb-alert
keycloak.url=http://localhost:8081
keycloak.client-id=tb-alert-frontend
keycloak.username=admin@admin.admin
keycloak.password=admin
keycloak.client-id-id=aa08979c-60ea-4401-b229-099d9ca25d6e

logging.level.org.springframework.security=DEBUG
#Scheduler
app.notification.timezone=Asia/Kolkata

#Plivo SMS Platform
plivo.auth.id=your_auth_id
plivo.auth.token=your_auth_token
app.notification.sender-id=your-sender-id
