spring.application.name=tb-alert-backend

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tbAlert
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Scheduler
app.threadPoolSize=10
app.notification.lead-time-seconds=1800
